@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Nov 20 16:43:47 -0500 2024
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Datapath_testbench_behav -key {Behavioral:sim_1:Functional:Datapath_testbench} -tclbatch Datapath_testbench.tcl -view C:/Users/chenh/Desktop/BU_Grad_EC605_LAB/Lab5/Project/Lab5/Datapath_testbench_behav.wcfg -log simulate.log"
call xsim  Datapath_testbench_behav -key {Behavioral:sim_1:Functional:Datapath_testbench} -tclbatch Datapath_testbench.tcl -view C:/Users/chenh/Desktop/BU_Grad_EC605_LAB/Lab5/Project/Lab5/Datapath_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
